### ISSUE TITLE
Exit Thread

### ISSUE THREAD

**Issue by fcarlier** [vichargrave/threads#2]
Bonjour,

In your main.cpp file, before to exit ('return NULL;') of run function (mail.cpp:L37),
you don't add 'pthread_exit(NULL);' 
It's normal ?

THX

**Comment by vichargrave** [comment]
When the application process quits it should take all the threads with it.

**Comment by fcarlier** [comment]
OK in my case, i have integrated this 'threads function' and your article 'Multithreaded Work Queue Based Server in C++' in my application but : 
in my main function, 

```
void handle_signal(int s)
 {
 alive = 0;
 };

int main(int argc, char** argv)
 {
 signal(SIGINT, handle_signal);
 signal(SIGTERM, handle_signal);
 start(); // execute start thread + other

while(alive) {
  sleep(1);
};
stop();
exit(0);
```

**\* Error in `./basic.bin': double free or corruption (!prev): 0x0000000000dae8c0 ***
*** Error in`./basic.bin': corrupted double-linked list: 0x00000000021e7d90 ***
The program is correctly executed but bad terminaison.

I think that it's double free allocation !! But I can not debug ;( I search :)

**Comment by fcarlier** [comment]
It's now okay ;)
The problem is 'new constructor' without 'delete destructor' ;)
THX
